---

exclude: ^.*\._py$

repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.3.0
   hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-toml
      exclude: ^repo_helper/templates/.*\.toml$
    - id: check-yaml
      exclude: ^repo_helper/templates/.*\.(yml|yaml)$
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-vcs-permalinks
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending

 - repo: https://github.com/domdfcoding/pre-commit-hooks
   rev: v0.1.6
   hooks:
    - id: requirements-txt-sorter
      args:
       - --allow-git
    - id: check-docstring-first
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup|tests/.*)\.py$
    - id: bind-requirements

 - repo: https://github.com/domdfcoding/flake8-dunder-all
   rev: v0.1.3
   hooks:
    - id: ensure-dunder-all
      files: ^repo_helper/.*\.py$

 - repo: https://github.com/pre-commit/pygrep-hooks
   rev: v1.7.0
   hooks:
    - id: python-no-eval
    - id: python-use-type-annotations

 - repo: https://github.com/asottile/pyupgrade
   rev: v2.7.4
   hooks:
    - id: pyupgrade
      args:
       - --py36-plus

 - repo: https://github.com/Lucas-C/pre-commit-hooks
   rev: v1.1.9
   hooks:
    - id: remove-crlf
    - id: forbid-crlf

 - repo: https://github.com/domdfcoding/yapf-isort
   rev: v0.5.4
   hooks:
    - id: yapf-isort
      exclude: ^(doc-source/conf|__pkginfo__|make_conda_recipe|setup|repo_helper/templates/.*)\.(_)?py$

 - repo: https://github.com/domdfcoding/dep_checker
   rev: v0.4.1
   hooks:
    - id: dep_checker
      args:
       - repo_helper
