# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi



jobs:
  allow_failures:
    - arch: arm64

  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64
    - python: '3.9-dev'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.7"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/repo_helper
        provider: pypi
        user: "DomDF"
        password:
          secure:
        distributions: "sdist bdist_wheel"
        skip_existing: true
