name: "GitHub Releases"
on:
  push:
  schedule:
   - cron: 0 12 * * 2,4,6

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: domdfcoding/octocheese@master
        with:
          pypi_name: "domdf_git_helper"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
